// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Product struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Brand       string `json:"brand"`
	PriceCents  int64  `json:"price_cents"`
	Currency    string `json:"currency"`
	ImageUrl    string `json:"image_url"`
	Tags        string `json:"tags"`
}
