// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetProduct(ctx context.Context, id string) (Product, error)
	ListAllProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
