// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, brand, price_cents, currency, image_url, tags
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.PriceCents,
		&i.Currency,
		&i.ImageUrl,
		&i.Tags,
	)
	return i, err
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, name, description, brand, price_cents, currency, image_url, tags
FROM products
ORDER BY name
`

func (q *Queries) ListAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.PriceCents,
			&i.Currency,
			&i.ImageUrl,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
