// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Stock struct {
	ProductID string `json:"product_id"`
	OnHand    int32  `json:"on_hand"`
	Reserved  int32  `json:"reserved"`
}
