// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetStock(ctx context.Context, productID string) (Stock, error)
	ListStockByIDs(ctx context.Context, productIds []string) ([]Stock, error)
	// ReleaseStock undoes a hold (compensation). GREATEST clamps at zero so a
	// duplicate/late release can never drive reserved negative (idempotent-safe).
	ReleaseStock(ctx context.Context, arg ReleaseStockParams) (Stock, error)
	// ReserveStock atomically holds `quantity` units: it succeeds (returns the row)
	// only when enough is sellable (on_hand - reserved >= quantity), otherwise it
	// matches no row and returns pgx.ErrNoRows — the saga's "insufficient stock"
	// signal. Callers run all of an order's items in one transaction so a partial
	// order never half-reserves.
	ReserveStock(ctx context.Context, arg ReserveStockParams) (Stock, error)
}

var _ Querier = (*Queries)(nil)
