// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const getStock = `-- name: GetStock :one
SELECT product_id, on_hand, reserved
FROM stock
WHERE product_id = $1
`

func (q *Queries) GetStock(ctx context.Context, productID string) (Stock, error) {
	row := q.db.QueryRow(ctx, getStock, productID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.OnHand, &i.Reserved)
	return i, err
}

const listStockByIDs = `-- name: ListStockByIDs :many
SELECT product_id, on_hand, reserved
FROM stock
WHERE product_id = ANY($1::text[])
`

func (q *Queries) ListStockByIDs(ctx context.Context, productIds []string) ([]Stock, error) {
	rows, err := q.db.Query(ctx, listStockByIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(&i.ProductID, &i.OnHand, &i.Reserved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseStock = `-- name: ReleaseStock :one
UPDATE stock
SET reserved = GREATEST(reserved - $1, 0)
WHERE product_id = $2
RETURNING product_id, on_hand, reserved
`

type ReleaseStockParams struct {
	Quantity  int32  `json:"quantity"`
	ProductID string `json:"product_id"`
}

// ReleaseStock undoes a hold (compensation). GREATEST clamps at zero so a
// duplicate/late release can never drive reserved negative (idempotent-safe).
func (q *Queries) ReleaseStock(ctx context.Context, arg ReleaseStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, releaseStock, arg.Quantity, arg.ProductID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.OnHand, &i.Reserved)
	return i, err
}

const reserveStock = `-- name: ReserveStock :one
UPDATE stock
SET reserved = reserved + $1
WHERE product_id = $2
  AND on_hand - reserved >= $1
RETURNING product_id, on_hand, reserved
`

type ReserveStockParams struct {
	Quantity  int32  `json:"quantity"`
	ProductID string `json:"product_id"`
}

// ReserveStock atomically holds `quantity` units: it succeeds (returns the row)
// only when enough is sellable (on_hand - reserved >= quantity), otherwise it
// matches no row and returns pgx.ErrNoRows — the saga's "insufficient stock"
// signal. Callers run all of an order's items in one transaction so a partial
// order never half-reserves.
func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, reserveStock, arg.Quantity, arg.ProductID)
	var i Stock
	err := row.Scan(&i.ProductID, &i.OnHand, &i.Reserved)
	return i, err
}
